server:
  port: 9005
  servlet:
    encoding:
      enabled: true
      force: true
      charset: UTF-8

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/hrdb?useUnicode=true&characterEncoding=utf8
    username: hruser
    password: hrpass
    driver-class-name: org.mariadb.jdbc.Driver

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  web:
    resources:
      static-locations: classpath:/static/,classpath:/public/

  jackson:
    time-zone: Asia/Seoul
    locale: ko_KR

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

logging:
  level:
    root: INFO
    com.songjunhyen.hrms: DEBUG
